import React from 'react'

const Link3 = () => {
  return (
    <div className='bg-slate-100 px-3 mx-auto mt-8'>
      <h2 className='font-semibold my-3'>Link3 Contents</h2>
      <p className='text-justify'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quos id perferendis veniam, mollitia praesentium, labore eligendi optio temporibus, eum facilis saepe dolore numquam harum officia magnam. Numquam dicta reprehenderit rerum voluptatum dolor maxime! Dolore obcaecati id sequi voluptates quisquam, ipsa officiis ex voluptatem ut dolor sapiente a incidunt assumenda aut illum aperiam iusto eveniet cum atque nulla nam tempora. Sit iusto optio voluptate deserunt corrupti voluptates. Sunt porro voluptas reiciendis dicta fugiat modi voluptatum exercitationem quos delectus sed nostrum numquam, dolore vero vel ipsum totam neque! Dignissimos, obcaecati laboriosam tempore aut modi magni aliquid eum a maxime, similique earum unde dolores laudantium minima ut ad nihil quis nemo ex! Quas pariatur culpa id dolorum iusto nulla numquam facere, itaque quia cum illum placeat deserunt. Ipsa fuga natus saepe quo iure vel sint corporis id facilis quod. Numquam, libero ad. Accusamus obcaecati fugit veritatis laboriosam laudantium tempora natus quidem magni. Blanditiis eveniet accusamus fuga in maiores aspernatur, eum beatae atque veritatis libero aliquid. Aut excepturi hic, minima illo nam odio eveniet iusto saepe harum quos velit perferendis optio dolorem dolore at eum mollitia. Nihil distinctio labore quibusdam doloremque facere, repudiandae enim aliquam tenetur saepe veniam accusamus, voluptatum ducimus doloribus tempore quo ut dolores pariatur magnam beatae quidem ipsum! Ad consectetur minima id ratione dolorem eos esse vel quis enim? Libero accusamus amet ipsum ducimus natus obcaecati dicta, in esse non excepturi laboriosam mollitia quod delectus eligendi sapiente enim! At laborum esse officia dolor asperiores aut, animi quis vel voluptates quae dolore adipisci explicabo inventore provident voluptatum corporis natus. Animi rerum consectetur provident voluptates obcaecati aliquam porro impedit enim numquam dolor et quam sapiente delectus illo sint aperiam dicta facilis, corrupti dolorem necessitatibus eum magnam voluptate. Dolor neque corrupti facilis sequi possimus qui sapiente aspernatur quibusdam perspiciatis amet velit fuga repellendus, porro mollitia incidunt tempore modi! Eligendi ducimus vitae nostrum eaque laborum, quidem nam? Praesentium nulla aperiam atque ad, unde incidunt, aut nesciunt dicta cumque id eligendi rem fuga molestiae pariatur, sint voluptatibus! Odio eum nulla iure illo dolor amet dicta. Tenetur exercitationem illum ex. Sed tempore necessitatibus reprehenderit provident, excepturi atque nulla mollitia accusamus debitis vel, fuga unde illo soluta? Libero harum pariatur sequi repellat, veritatis amet sint neque deserunt doloribus ea recusandae laudantium dolor temporibus, voluptatum exercitationem quibusdam blanditiis soluta? Beatae fugiat impedit minus mollitia sequi animi, quos sunt? Aliquid esse laudantium ipsum hic aliquam veritatis maxime. Numquam, alias itaque.</p>
    </div>
  )
}

export default Link3
